defaults:
  - _self_
  - model: base

weights: weights/cutie-base-mega.pth

# All "size" parameters represent the length of the shorter edge
# maximum internal processing size; reducing this speeds up processing
max_internal_size: 480

# Disable long-term memory for cell tracking
use_long_term: False

# Add memory every frame for immediate tracking
mem_every: 1

# Use minimal top_k for efficiency
top_k: 10

# Update every frame
stagger_updates: 1

# Process objects one by one to reduce memory usage
chunk_size: 1

save_aux: False
flip_aug: False

# Only keep 1 frame in working memory (essentially frame-by-frame)
max_mem_frames: 1

# Long-term memory settings (unused but kept for compatibility)
long_term:
  count_usage: True
  max_mem_frames: 10
  min_mem_frames: 5
  num_prototypes: 128
  max_num_tokens: 10000
  buffer_tokens: 2000
